<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>CooldownMunitions</AssemblyName>
    <RootNamespace>CooldownMunitions</RootNamespace>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>..\..\core\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>..\..\core\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\..\..\NuclearOption_Data\Managed\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\..\..\NuclearOption_Data\Managed\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\..\NuclearOption_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Mirage">
      <HintPath>..\..\..\NuclearOption_Data\Managed\Mirage.dll</HintPath>
    </Reference>
    <Reference Include="UniTask">
      <HintPath>..\..\..\NuclearOption_Data\Managed\UniTask.dll</HintPath>
    </Reference>
  </ItemGroup>

  <Target Name="CopyOutputToPlugins" AfterTargets="Build">
    <Message Text="Copying built DLL to Plugins folder." Importance="High" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ProjectDir)..\..\Plugins\CooldownMunitions" SkipUnchangedFiles="true" />
  </Target>
</Project>
